##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  Wed Feb  3 13:09:43 2021

##  Generated by MIG Version 4.2
##
##################################################################################################
##  File name :       mig_7series_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K160T-FFG676
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M16XX-125
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_CK_N[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_CK_P[0]}]

#create_clock -period 2.5 -name clk_mig [get_ports MIGS_CLKP]

#create_clock -period 5 [get_ports clk_ref_i]
# Note: the following CLOCK_DEDICATED_ROUTE constraint will cause a warning in place similar
# to the following:
#   WARNING:Place:1402 - A clock IOB / PLL clock component pair have been found that are not
#   placed at an optimal clock IOB / PLL site pair.
# This warning can be ignored.  See the Users Guide for more information.
# The below constraint is used because the System Clock connecting to the PLL is
# not allocated in the same bank as the PLL itself.
# Please refer to UG 586 for details on clocking resources.
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets MIGS_CLKP]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_pins -hierarchical *pll*CLKIN1]


############## NET - IOSTANDARD ##################


# PadFunction: IO_L24P_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[0]}]
set_property PACKAGE_PIN AF10 [get_ports {DDR3_DQ[0]}]

# PadFunction: IO_L20P_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[1]}]
set_property PACKAGE_PIN AD10 [get_ports {DDR3_DQ[1]}]

# PadFunction: IO_L24N_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[2]}]
set_property PACKAGE_PIN AF9 [get_ports {DDR3_DQ[2]}]

# PadFunction: IO_L23N_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[3]}]
set_property PACKAGE_PIN AF13 [get_ports {DDR3_DQ[3]}]

# PadFunction: IO_L22P_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[4]}]
set_property PACKAGE_PIN AE8 [get_ports {DDR3_DQ[4]}]

# PadFunction: IO_L23P_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[5]}]
set_property PACKAGE_PIN AE13 [get_ports {DDR3_DQ[5]}]

# PadFunction: IO_L22N_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[6]}]
set_property PACKAGE_PIN AF8 [get_ports {DDR3_DQ[6]}]

# PadFunction: IO_L20N_T3_33
set_property SLEW FAST [get_ports {DDR3_DQ[7]}]
set_property PACKAGE_PIN AE10 [get_ports {DDR3_DQ[7]}]

# PadFunction: IO_L24P_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[8]}]
set_property PACKAGE_PIN AF3 [get_ports {DDR3_DQ[8]}]

# PadFunction: IO_L22N_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[9]}]
set_property PACKAGE_PIN AE2 [get_ports {DDR3_DQ[9]}]

# PadFunction: IO_L23P_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[10]}]
set_property PACKAGE_PIN AE6 [get_ports {DDR3_DQ[10]}]

# PadFunction: IO_L20N_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[11]}]
set_property PACKAGE_PIN AE1 [get_ports {DDR3_DQ[11]}]

# PadFunction: IO_L19P_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[12]}]
set_property PACKAGE_PIN AD4 [get_ports {DDR3_DQ[12]}]

# PadFunction: IO_L24N_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[13]}]
set_property PACKAGE_PIN AF2 [get_ports {DDR3_DQ[13]}]

# PadFunction: IO_L23N_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[14]}]
set_property PACKAGE_PIN AE5 [get_ports {DDR3_DQ[14]}]

# PadFunction: IO_L22P_T3_34
set_property SLEW FAST [get_ports {DDR3_DQ[15]}]
set_property PACKAGE_PIN AE3 [get_ports {DDR3_DQ[15]}]

# PadFunction: IO_L12N_T1_MRCC_34
set_property SLEW FAST [get_ports {DDR3_ADDR[13]}]
set_property PACKAGE_PIN AA2 [get_ports {DDR3_ADDR[13]}]

# PadFunction: IO_L17N_T2_34
set_property SLEW FAST [get_ports {DDR3_ADDR[12]}]
set_property PACKAGE_PIN Y5 [get_ports {DDR3_ADDR[12]}]

# PadFunction: IO_L17P_T2_34
set_property SLEW FAST [get_ports {DDR3_ADDR[11]}]
set_property PACKAGE_PIN Y6 [get_ports {DDR3_ADDR[11]}]

# PadFunction: IO_L18N_T2_34
set_property SLEW FAST [get_ports {DDR3_ADDR[10]}]
set_property PACKAGE_PIN AD5 [get_ports {DDR3_ADDR[10]}]

# PadFunction: IO_L7N_T1_34
set_property SLEW FAST [get_ports {DDR3_ADDR[9]}]
set_property PACKAGE_PIN Y2 [get_ports {DDR3_ADDR[9]}]

# PadFunction: IO_L16P_T2_34
set_property SLEW FAST [get_ports {DDR3_ADDR[8]}]
set_property PACKAGE_PIN AB6 [get_ports {DDR3_ADDR[8]}]

# PadFunction: IO_L8N_T1_34
set_property SLEW FAST [get_ports {DDR3_ADDR[7]}]
set_property PACKAGE_PIN V1 [get_ports {DDR3_ADDR[7]}]

# PadFunction: IO_L18P_T2_34
set_property SLEW FAST [get_ports {DDR3_ADDR[6]}]
set_property PACKAGE_PIN AD6 [get_ports {DDR3_ADDR[6]}]

# PadFunction: IO_L10P_T1_34
set_property SLEW FAST [get_ports {DDR3_ADDR[5]}]
set_property PACKAGE_PIN W1 [get_ports {DDR3_ADDR[5]}]

# PadFunction: IO_L16N_T2_34
set_property SLEW FAST [get_ports {DDR3_ADDR[4]}]
set_property PACKAGE_PIN AC6 [get_ports {DDR3_ADDR[4]}]

# PadFunction: IO_L10N_T1_34
set_property SLEW FAST [get_ports {DDR3_ADDR[3]}]
set_property PACKAGE_PIN Y1 [get_ports {DDR3_ADDR[3]}]

# PadFunction: IO_L9N_T1_DQS_34
set_property SLEW FAST [get_ports {DDR3_ADDR[2]}]
set_property PACKAGE_PIN AC1 [get_ports {DDR3_ADDR[2]}]

# PadFunction: IO_L13P_T2_MRCC_34
set_property SLEW FAST [get_ports {DDR3_ADDR[1]}]
set_property PACKAGE_PIN AA4 [get_ports {DDR3_ADDR[1]}]

# PadFunction: IO_L9P_T1_DQS_34
set_property SLEW FAST [get_ports {DDR3_ADDR[0]}]
set_property PACKAGE_PIN AB1 [get_ports {DDR3_ADDR[0]}]

# PadFunction: IO_L14P_T2_SRCC_34
set_property SLEW FAST [get_ports {DDR3_BA[2]}]
set_property PACKAGE_PIN AC4 [get_ports {DDR3_BA[2]}]

# PadFunction: IO_L13N_T2_MRCC_34
set_property SLEW FAST [get_ports {DDR3_BA[1]}]
set_property PACKAGE_PIN AB4 [get_ports {DDR3_BA[1]}]

# PadFunction: IO_L14N_T2_SRCC_34
set_property SLEW FAST [get_ports {DDR3_BA[0]}]
set_property PACKAGE_PIN AC3 [get_ports {DDR3_BA[0]}]

# PadFunction: IO_L11N_T1_SRCC_34
set_property SLEW FAST [get_ports DDR3_RAS_N]
set_property IOSTANDARD SSTL15 [get_ports DDR3_RAS_N]
set_property PACKAGE_PIN AC2 [get_ports DDR3_RAS_N]

# PadFunction: IO_L11P_T1_SRCC_34
set_property SLEW FAST [get_ports DDR3_CAS_N]
set_property IOSTANDARD SSTL15 [get_ports DDR3_CAS_N]
set_property PACKAGE_PIN AB2 [get_ports DDR3_CAS_N]

# PadFunction: IO_L12P_T1_MRCC_34
set_property SLEW FAST [get_ports DDR3_WE_N]
set_property IOSTANDARD SSTL15 [get_ports DDR3_WE_N]
set_property PACKAGE_PIN AA3 [get_ports DDR3_WE_N]

# PadFunction: IO_L16N_T2_33
set_property SLEW FAST [get_ports DDR3_RESET_N]
set_property IOSTANDARD LVCMOS15 [get_ports DDR3_RESET_N]
set_property PACKAGE_PIN AA12 [get_ports DDR3_RESET_N]

# PadFunction: IO_L3P_T0_DQS_34
set_property SLEW FAST [get_ports {DDR3_CKE[0]}]
set_property PACKAGE_PIN W6 [get_ports {DDR3_CKE[0]}]

# PadFunction: IO_L3N_T0_DQS_34
set_property SLEW FAST [get_ports {DDR3_ODT[0]}]
set_property PACKAGE_PIN W5 [get_ports {DDR3_ODT[0]}]

# PadFunction: IO_L7P_T1_34
set_property SLEW FAST [get_ports {DDR3_CS_N[0]}]
set_property PACKAGE_PIN Y3 [get_ports {DDR3_CS_N[0]}]

# PadFunction: IO_L19P_T3_33
set_property SLEW FAST [get_ports {DDR3_DM[0]}]
set_property PACKAGE_PIN AD11 [get_ports {DDR3_DM[0]}]

# PadFunction: IO_L20P_T3_34
set_property SLEW FAST [get_ports {DDR3_DM[1]}]
set_property PACKAGE_PIN AD1 [get_ports {DDR3_DM[1]}]

# PadFunction: IO_L14P_T2_SRCC_33
#set_property IOSTANDARD DIFF_SSTL15 [get_ports {MIGS_CLKP}]
set_property IOSTANDARD LVDS [get_ports MIGS_CLKP]

# PadFunction: IO_L14N_T2_SRCC_33
#set_property IOSTANDARD DIFF_SSTL15 [get_ports {MIGS_CLKN}]
set_property IOSTANDARD LVDS [get_ports MIGS_CLKN]
set_property PACKAGE_PIN AA10 [get_ports MIGS_CLKP]
set_property PACKAGE_PIN AB10 [get_ports MIGS_CLKN]

# PadFunction: IO_L21P_T3_DQS_33
set_property SLEW FAST [get_ports {DDR3_DQS_P[0]}]

# PadFunction: IO_L21N_T3_DQS_33
set_property SLEW FAST [get_ports {DDR3_DQS_N[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR3_DQS_N[0]}]
set_property PACKAGE_PIN AE12 [get_ports {DDR3_DQS_P[0]}]
set_property PACKAGE_PIN AF12 [get_ports {DDR3_DQS_N[0]}]

# PadFunction: IO_L21P_T3_DQS_34
set_property SLEW FAST [get_ports {DDR3_DQS_P[1]}]

# PadFunction: IO_L21N_T3_DQS_34
set_property SLEW FAST [get_ports {DDR3_DQS_N[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR3_DQS_N[1]}]
set_property PACKAGE_PIN AF5 [get_ports {DDR3_DQS_P[1]}]
set_property PACKAGE_PIN AF4 [get_ports {DDR3_DQS_N[1]}]

# PadFunction: IO_L15P_T2_DQS_34
set_property SLEW FAST [get_ports {DDR3_CK_P[0]}]

# PadFunction: IO_L15N_T2_DQS_34
set_property SLEW FAST [get_ports {DDR3_CK_N[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_CK_N[0]}]
set_property PACKAGE_PIN AA5 [get_ports {DDR3_CK_P[0]}]
set_property PACKAGE_PIN AB5 [get_ports {DDR3_CK_N[0]}]




set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y8 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]


set_property LOC PHASER_IN_PHY_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y8 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property LOC OUT_FIFO_X1Y11 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X1Y10 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X1Y9 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X1Y8 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]


set_property LOC IN_FIFO_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X1Y8 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X1Y1 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property LOC PHY_CONTROL_X1Y2 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X1Y1 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property LOC PHASER_REF_X1Y2 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X1Y57 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X1Y107 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]



set_multicycle_path -setup -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 6

set_multicycle_path -hold -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 5

set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -setup -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 2
set_multicycle_path -hold -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 1

#set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_max_delay -to [get_pins -hier -include_replicated_objects -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1_reg[*]/D}] 20.000
set_max_delay -datapath_only -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] 5.000
#set_false_path -through [get_pins -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst}]
set_false_path -through [get_nets -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst_i}]





